// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Consumption {
    /**
     * Creates a new Consumption instance.
     * @param {Partial<Consumption>} [$$source = {}] - The source object to create the Consumption.
     */
    constructor($$source = {}) {
        if (!("Key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Key"] = "";
        }
        if (!("TaskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TaskID"] = "";
        }
        if (!("TradeDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TradeDate"] = "";
        }
        if (!("Account" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Account"] = "";
        }
        if (!("StorageType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StorageType"] = "";
        }
        if (!("SerialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SerialNumber"] = "";
        }
        if (!("Currency" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Currency"] = "";
        }
        if (!("CashOrRemit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CashOrRemit"] = "";
        }
        if (!("Summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Summary"] = "";
        }
        if (!("Region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Region"] = "";
        }
        if (!("IncomeOrExpenseAmount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["IncomeOrExpenseAmount"] = 0;
        }
        if (!("Balance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Balance"] = 0;
        }
        if (!("Channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Consumption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Consumption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Consumption(/** @type {Partial<Consumption>} */($$parsedSource));
    }
}
