// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Consumption {
    "Key": string;
    "TaskID": string;
    "TradeDate": string;
    "Account": string;
    "StorageType": string;
    "SerialNumber": string;
    "Currency": string;
    "CashOrRemit": string;
    "Summary": string;
    "Region": string;
    "IncomeOrExpenseAmount": number;
    "Balance": number;
    "Channel": string;

    /** Creates a new Consumption instance. */
    constructor($$source: Partial<Consumption> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("TaskID" in $$source)) {
            this["TaskID"] = "";
        }
        if (!("TradeDate" in $$source)) {
            this["TradeDate"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("StorageType" in $$source)) {
            this["StorageType"] = "";
        }
        if (!("SerialNumber" in $$source)) {
            this["SerialNumber"] = "";
        }
        if (!("Currency" in $$source)) {
            this["Currency"] = "";
        }
        if (!("CashOrRemit" in $$source)) {
            this["CashOrRemit"] = "";
        }
        if (!("Summary" in $$source)) {
            this["Summary"] = "";
        }
        if (!("Region" in $$source)) {
            this["Region"] = "";
        }
        if (!("IncomeOrExpenseAmount" in $$source)) {
            this["IncomeOrExpenseAmount"] = 0;
        }
        if (!("Balance" in $$source)) {
            this["Balance"] = 0;
        }
        if (!("Channel" in $$source)) {
            this["Channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Consumption instance from a string or object.
     */
    static createFrom($$source: any = {}): Consumption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Consumption($$parsedSource as Partial<Consumption>);
    }
}
