// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// consumptionsDao is the data access object for the table consumptions.
// You can define custom methods on it to extend its functionality as needed.
type consumptionsDao struct {
	*internal.ConsumptionsDao
}

var (
	// Consumptions is a globally accessible object for table consumptions operations.
	Consumptions = consumptionsDao{internal.NewConsumptionsDao()}
)

// Add your custom methods and functionality below.
