// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// exportsDao is the data access object for the table exports.
// You can define custom methods on it to extend its functionality as needed.
type exportsDao struct {
	*internal.ExportsDao
}

var (
	// Exports is a globally accessible object for table exports operations.
	Exports = exportsDao{internal.NewExportsDao()}
)

// Add your custom methods and functionality below.
