// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// kvStoreDao is the data access object for the table kv_store.
// You can define custom methods on it to extend its functionality as needed.
type kvStoreDao struct {
	*internal.KvStoreDao
}

var (
	// KvStore is a globally accessible object for table kv_store operations.
	KvStore = kvStoreDao{internal.NewKvStoreDao()}
)

// Add your custom methods and functionality below.
