// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// pausePointsDao is the data access object for the table pause_points.
// You can define custom methods on it to extend its functionality as needed.
type pausePointsDao struct {
	*internal.PausePointsDao
}

var (
	// PausePoints is a globally accessible object for table pause_points operations.
	PausePoints = pausePointsDao{internal.NewPausePointsDao()}
)

// Add your custom methods and functionality below.
