// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// systemParametersDao is the data access object for the table system_parameters.
// You can define custom methods on it to extend its functionality as needed.
type systemParametersDao struct {
	*internal.SystemParametersDao
}

var (
	// SystemParameters is a globally accessible object for table system_parameters operations.
	SystemParameters = systemParametersDao{internal.NewSystemParametersDao()}
)

// Add your custom methods and functionality below.
