// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// systemParameterOptionsDao is the data access object for the table system_parameter_options.
// You can define custom methods on it to extend its functionality as needed.
type systemParameterOptionsDao struct {
	*internal.SystemParameterOptionsDao
}

var (
	// SystemParameterOptions is a globally accessible object for table system_parameter_options operations.
	SystemParameterOptions = systemParameterOptionsDao{internal.NewSystemParameterOptionsDao()}
)

// Add your custom methods and functionality below.
