// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// tasksDao is the data access object for the table tasks.
// You can define custom methods on it to extend its functionality as needed.
type tasksDao struct {
	*internal.TasksDao
}

var (
	// Tasks is a globally accessible object for table tasks operations.
	Tasks = tasksDao{internal.NewTasksDao()}
)

// Add your custom methods and functionality below.
