// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// taskChannelsDao is the data access object for the table task_channels.
// You can define custom methods on it to extend its functionality as needed.
type taskChannelsDao struct {
	*internal.TaskChannelsDao
}

var (
	// TaskChannels is a globally accessible object for table task_channels operations.
	TaskChannels = taskChannelsDao{internal.NewTaskChannelsDao()}
)

// Add your custom methods and functionality below.
