// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"helpfly/internal/dao/internal"
)

// taskSummariesDao is the data access object for the table task_summaries.
// You can define custom methods on it to extend its functionality as needed.
type taskSummariesDao struct {
	*internal.TaskSummariesDao
}

var (
	// TaskSummaries is a globally accessible object for table task_summaries operations.
	TaskSummaries = taskSummariesDao{internal.NewTaskSummariesDao()}
)

// Add your custom methods and functionality below.
