// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DbService 数据库服务结构体，提供基础的数据库操作接口
 * 该服务通过 Wails 框架暴露给前端调用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./db/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddConsumption 新增一条消费记录（用于前端账单表格打通后端演示）
 * @param {db$0.Consumption} record
 * @returns {$CancellablePromise<any>}
 */
export function AddConsumption(record) {
    return $Call.ByID(1397313034, record);
}

/**
 * CancelTask 取消正在运行的任务
 * 参数:
 *   - taskID: 任务ID
 * 
 * 返回值:
 *   - string: 成功返回"任务已取消"
 *   - error: 如果任务不存在或未在运行返回错误
 * 
 * 注意: 取消后会延迟1分钟清理进度信息，以便前端获取最终状态
 * @param {string} taskID
 * @returns {$CancellablePromise<string>}
 */
export function CancelTask(taskID) {
    return $Call.ByID(4218483403, taskID);
}

/**
 * CreateTask 创建新任务并持久化到数据库
 * 参数:
 *   - payload: 任务数据载荷
 * 
 * 返回值:
 *   - TaskRecord: 创建的任务记录（包含生成的TaskID和Key）
 *   - error: 如果创建失败返回错误
 * 
 * 注意: 任务状态默认为0（未开始）
 * @param {$models.TaskPayload} payload
 * @returns {$CancellablePromise<$models.TaskRecord>}
 */
export function CreateTask(payload) {
    return $Call.ByID(259175413, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteConsumptions 批量删除消费记录
 * 参数:
 *   - keys: 要删除的消费记录Key列表
 * 
 * 返回值:
 *   - string: 成功返回"success"
 *   - error: 如果删除失败返回错误
 * @param {string[]} keys
 * @returns {$CancellablePromise<string>}
 */
export function DeleteConsumptions(keys) {
    return $Call.ByID(3677077451, keys);
}

/**
 * DeleteConsumptionsByTaskID 删除指定任务的所有消费记录
 * 该方法异步执行，实时更新删除进度，支持并发执行多个删除任务
 * 参数:
 *   - taskID: 任务ID
 * 
 * 返回值:
 *   - string: 成功返回"删除已启动"
 *   - error: 如果参数无效或删除已在运行返回错误
 * @param {string} taskID
 * @returns {$CancellablePromise<string>}
 */
export function DeleteConsumptionsByTaskID(taskID) {
    return $Call.ByID(433906950, taskID);
}

/**
 * DeleteExports 批量删除导出记录
 * 参数:
 *   - keys: 要删除的导出记录Key列表
 * 
 * 返回值:
 *   - string: 成功返回"success"
 *   - error: 如果删除失败返回错误
 * @param {string[]} keys
 * @returns {$CancellablePromise<string>}
 */
export function DeleteExports(keys) {
    return $Call.ByID(491765242, keys);
}

/**
 * DeleteTasks 批量删除任务
 * 参数:
 *   - keys: 要删除的任务Key列表
 * 
 * 返回值:
 *   - string: 成功返回"success"
 *   - error: 如果删除失败返回错误
 * 
 * 注意: 删除任务时会自动取消正在运行的任务并清理进度信息
 * @param {string[]} keys
 * @returns {$CancellablePromise<string>}
 */
export function DeleteTasks(keys) {
    return $Call.ByID(971878207, keys);
}

/**
 * ExportConsumptionsToExcel 将消费记录导出为 Excel 并保存到数据库
 * 参数:
 *   - taskID: 任务ID，如果为空则导出所有任务的消费记录
 *   - keys: 要导出的消费记录Key列表，如果为空则导出所有记录
 * 
 * 返回值:
 *   - string: 导出记录的唯一标识符
 *   - error: 如果导出失败返回错误
 * @param {string} taskID
 * @param {string[]} keys
 * @returns {$CancellablePromise<string>}
 */
export function ExportConsumptionsToExcel(taskID, keys) {
    return $Call.ByID(3287970074, taskID, keys);
}

/**
 * ExportConsumptionsToPDF 将消费记录导出为 PDF 并保存到数据库
 * 参数:
 *   - taskID: 任务ID，如果为空则导出所有任务的消费记录
 *   - keys: 要导出的消费记录Key列表，如果为空则导出所有记录
 * 
 * 返回值:
 *   - string: 导出记录的唯一标识符
 *   - error: 如果导出失败返回错误
 * @param {string} taskID
 * @param {string[]} keys
 * @returns {$CancellablePromise<string>}
 */
export function ExportConsumptionsToPDF(taskID, keys) {
    return $Call.ByID(2326109015, taskID, keys);
}

/**
 * GenerateConsumptions 根据任务参数生成消费记录
 * 该方法异步执行，实时更新任务进度，支持并发执行多个任务
 * 参数:
 *   - task: 任务记录，包含生成消费记录所需的所有参数
 *   - doType: 操作类型，"pause"表示暂停任务，"resume"表示恢复任务，空字符串表示正常启动任务
 * 
 * 返回值:
 *   - string: 成功返回"任务已启动"、"任务已暂停"或"任务已恢复"
 *   - error: 如果参数无效或任务已在运行返回错误
 * 
 * 生成逻辑:
 *   - 交易日期：在TransactionDateRange范围内随机生成
 *   - 渠道：从Channels列表中随机选择一个
 *   - 摘要：从Summaries列表中随机选择一个
 *   - 金额：根据AmountType规则生成（规则一：0-1000正数，规则二：-1000-0负数，默认：-1000到1000随机）
 *   - 余额：从OpeningBalance开始，每笔交易累加
 * @param {$models.TaskRecord} task
 * @param {string} doType
 * @returns {$CancellablePromise<string>}
 */
export function GenerateConsumptions(task, doType) {
    return $Call.ByID(1336699271, task, doType);
}

/**
 * GetData 从数据库中获取测试数据
 * 返回值: 如果成功返回数据字符串，失败返回错误信息
 * @returns {$CancellablePromise<any>}
 */
export function GetData() {
    return $Call.ByID(3006785016);
}

/**
 * GetDefaultExportPath 获取默认导出路径
 * 返回值:
 *   - string: 默认导出路径（系统下载目录下的 bill_help/export/）
 *   - error: 如果获取失败返回错误
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultExportPath() {
    return $Call.ByID(2486696236);
}

/**
 * GetDeleteProgress 获取指定任务的删除进度
 * 参数:
 *   - taskID: 任务ID
 * 
 * 返回值:
 *   - TaskProgress: 删除进度信息
 *   - error: 如果任务不存在返回错误
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.TaskProgress | null>}
 */
export function GetDeleteProgress(taskID) {
    return $Call.ByID(1239138612, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetExportPath 获取当前设置的导出路径
 * 返回值:
 *   - string: 导出路径（绝对路径）
 *   - error: 如果获取失败返回错误
 * @returns {$CancellablePromise<string>}
 */
export function GetExportPath() {
    return $Call.ByID(2358337533);
}

/**
 * GetSystemParameters 获取系统参数
 * 返回值:
 *   - SystemParameters: 系统参数
 *   - error: 如果获取失败返回错误
 * @returns {$CancellablePromise<$models.SystemParameters>}
 */
export function GetSystemParameters() {
    return $Call.ByID(3269872581).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTaskProgress 获取指定任务的当前进度
 * 参数:
 *   - taskID: 任务ID
 * 
 * 返回值:
 *   - TaskProgress: 任务进度信息
 *   - error: 如果任务不存在返回错误
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.TaskProgress | null>}
 */
export function GetTaskProgress(taskID) {
    return $Call.ByID(4185893318, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListConsumptions 获取消费记录列表
 * 参数:
 *   - taskID: 任务ID，如果为空字符串则返回所有任务的消费记录
 * 
 * 返回值:
 *   - []ConsumptionRecord: 消费记录列表，按序号升序排列
 *   - error: 如果获取失败返回错误
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.ConsumptionRecord[]>}
 */
export function ListConsumptions(taskID) {
    return $Call.ByID(2900707616, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListExports 获取所有导出记录
 * 返回值:
 *   - []ExportRecord: 导出记录列表，按创建时间倒序排列（最新的在前）
 *   - error: 如果获取失败返回错误
 * @returns {$CancellablePromise<$models.ExportRecord[]>}
 */
export function ListExports() {
    return $Call.ByID(584533691).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListTasks 获取所有任务记录列表
 * 返回值:
 *   - []TaskRecord: 任务记录列表，按创建时间倒序排列（最新的在前）
 *   - error: 如果获取失败返回错误
 * @returns {$CancellablePromise<$models.TaskRecord[]>}
 */
export function ListTasks() {
    return $Call.ByID(3250811470).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * OpenFolder 打开指定文件夹，如果是文件路径则选中该文件
 * 参数:
 *   - path: 文件夹路径或文件路径
 * 
 * 返回值:
 *   - string: 成功返回"success"
 *   - error: 如果打开失败返回错误
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFolder(path) {
    return $Call.ByID(710236192, path);
}

/**
 * SaveSystemParameters 保存系统参数
 * 参数:
 *   - params: 系统参数
 * 
 * 返回值:
 *   - string: 成功返回"保存成功"
 *   - error: 如果保存失败返回错误
 * @param {$models.SystemParameters} params
 * @returns {$CancellablePromise<string>}
 */
export function SaveSystemParameters(params) {
    return $Call.ByID(53176932, params);
}

/**
 * SearchConsumptions 根据任务ID与关键词检索消费记录
 * 参数:
 *   - taskID: 任务ID
 *   - keyword: 搜索关键词
 * 
 * 返回值:
 *   - []ConsumptionRecord: 匹配的消费记录列表
 *   - error: 如果获取失败返回错误
 * @param {string} taskID
 * @param {string} keyword
 * @returns {$CancellablePromise<$models.ConsumptionRecord[]>}
 */
export function SearchConsumptions(taskID, keyword) {
    return $Call.ByID(3965766772, taskID, keyword).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SearchExports 根据关键词搜索导出记录
 * 参数:
 *   - keyword: 搜索关键词
 * 
 * 返回值:
 *   - []ExportRecord: 匹配的导出记录列表
 *   - error: 如果获取失败返回错误
 * @param {string} keyword
 * @returns {$CancellablePromise<$models.ExportRecord[]>}
 */
export function SearchExports(keyword) {
    return $Call.ByID(3369269735, keyword).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SearchTasks 根据关键词筛选任务记录
 * 关键词会在 taskId、taskName、accountName、account、bank、currency 等字段中匹配
 * @param {string} keyword
 * @returns {$CancellablePromise<$models.TaskRecord[]>}
 */
export function SearchTasks(keyword) {
    return $Call.ByID(2192696634, keyword).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SelectExportPath 打开文件夹选择对话框
 * 参数:
 *   - defaultPath: 默认路径，如果为空则使用系统默认导出路径
 * 
 * 返回值:
 *   - string: 用户选择的文件夹路径（绝对路径）
 *   - error: 如果选择失败返回错误
 * @param {string} defaultPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectExportPath(defaultPath) {
    return $Call.ByID(3414901353, defaultPath);
}

/**
 * SelectWatermarkImage 打开 PNG 图片选择对话框。
 * @returns {$CancellablePromise<string>}
 */
export function SelectWatermarkImage() {
    return $Call.ByID(4238078643);
}

/**
 * SetData 保存数据到数据库
 * 参数:
 *   - param: 要保存的字符串数据
 * 
 * 返回值: 保存成功后返回保存的数据，失败返回错误
 * @param {string} param
 * @returns {$CancellablePromise<any>}
 */
export function SetData(param) {
    return $Call.ByID(2821368580, param);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<$models.PromiseResult | null>}
 */
export function TestPromiose(key) {
    return $Call.ByID(3826025258, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * UpdateConsumption 根据 Key 更新一条消费记录（用于前端账单表格打通后端演示）
 * @param {db$0.Consumption} record
 * @returns {$CancellablePromise<any>}
 */
export function UpdateConsumption(record) {
    return $Call.ByID(3211795332, record);
}

/**
 * UpdateTask 更新已存在的任务记录
 * 参数:
 *   - record: 包含更新数据的任务记录（必须包含Key字段）
 * 
 * 返回值:
 *   - TaskRecord: 更新后的任务记录
 *   - error: 如果更新失败返回错误
 * 
 * 注意: 如果record中TaskID或CreatedAt为空，会从现有记录中继承
 * @param {$models.TaskRecord} record
 * @returns {$CancellablePromise<$models.TaskRecord>}
 */
export function UpdateTask(record) {
    return $Call.ByID(2085643228, record).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TaskRecord.createFrom;
const $$createType1 = $models.TaskProgress.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.SystemParameters.createFrom;
const $$createType4 = $models.ConsumptionRecord.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ExportRecord.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = $models.PromiseResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
