// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(1569433126, name);
}

/**
 * 设置主题
 */
export function SetTheme(): $CancellablePromise<void> {
    return $Call.ByID(107562864);
}
