// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * 测试在Service中http-GET请求
 */
export function GetData(param: string): $CancellablePromise<any> {
    return $Call.ByID(112715374, param);
}

/**
 * 测试在Service中http-POST请求
 */
export function PostData(param: string): $CancellablePromise<any> {
    return $Call.ByID(1906529580, param);
}
