// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConsumptionRecord 消费记录结构体
 * 表示一条银行交易消费记录，包含交易的所有详细信息
 */
export class ConsumptionRecord {
    /**
     * Creates a new ConsumptionRecord instance.
     * @param {Partial<ConsumptionRecord>} [$$source = {}] - The source object to create the ConsumptionRecord.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * 数据库存储键，唯一标识符
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("taskId" in $$source)) {
            /**
             * 关联的任务ID
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("tradeDate" in $$source)) {
            /**
             * 交易日期时间（格式：2006-01-02 15:04:05）
             * @member
             * @type {string}
             */
            this["tradeDate"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * 账号
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("storageType" in $$source)) {
            /**
             * 储种（活期/定期）
             * @member
             * @type {string}
             */
            this["storageType"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * 序号（允许任意字符串）
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("currency" in $$source)) {
            /**
             * 币种（人民币/美元）
             * @member
             * @type {string}
             */
            this["currency"] = "";
        }
        if (!("cashOrRemit" in $$source)) {
            /**
             * 钞汇类型（钞/汇）
             * @member
             * @type {string}
             */
            this["cashOrRemit"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * 摘要（消费/工资/银联消费等）
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * 地区（北京/上海/广州等）
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("incomeOrExpenseAmount" in $$source)) {
            /**
             * 收入/支出金额（正数为收入，负数为支出）
             * @member
             * @type {number}
             */
            this["incomeOrExpenseAmount"] = 0;
        }
        if (!("balance" in $$source)) {
            /**
             * 余额（累加计算）
             * @member
             * @type {number}
             */
            this["balance"] = 0;
        }
        if (!("channel" in $$source)) {
            /**
             * 渠道（快捷支付/网上银行等）
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumptionRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConsumptionRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumptionRecord(/** @type {Partial<ConsumptionRecord>} */($$parsedSource));
    }
}

/**
 * ExportRecord 导出记录结构体
 * 表示一条PDF导出记录
 */
export class ExportRecord {
    /**
     * Creates a new ExportRecord instance.
     * @param {Partial<ExportRecord>} [$$source = {}] - The source object to create the ExportRecord.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * 数据库存储键，唯一标识符
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("taskId" in $$source)) {
            /**
             * 关联的任务ID
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * PDF文件保存路径
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * 导出时间
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRecord(/** @type {Partial<ExportRecord>} */($$parsedSource));
    }
}

export class PromiseResult {
    /**
     * Creates a new PromiseResult instance.
     * @param {Partial<PromiseResult>} [$$source = {}] - The source object to create the PromiseResult.
     */
    constructor($$source = {}) {
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromiseResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PromiseResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromiseResult(/** @type {Partial<PromiseResult>} */($$parsedSource));
    }
}

/**
 * SystemParameters 系统参数结构体
 * 用于存储系统配置参数，包括各种选项列表
 */
export class SystemParameters {
    /**
     * Creates a new SystemParameters instance.
     * @param {Partial<SystemParameters>} [$$source = {}] - The source object to create the SystemParameters.
     */
    constructor($$source = {}) {
        if (!("banks" in $$source)) {
            /**
             * 银行选项列表
             * @member
             * @type {string[]}
             */
            this["banks"] = [];
        }
        if (!("depositTypes" in $$source)) {
            /**
             * 储种选项列表
             * @member
             * @type {string[]}
             */
            this["depositTypes"] = [];
        }
        if (!("cashExchanges" in $$source)) {
            /**
             * 钞汇选项列表
             * @member
             * @type {string[]}
             */
            this["cashExchanges"] = [];
        }
        if (!("currencies" in $$source)) {
            /**
             * 币种选项列表
             * @member
             * @type {string[]}
             */
            this["currencies"] = [];
        }
        if (!("channels" in $$source)) {
            /**
             * 渠道选项列表
             * @member
             * @type {string[]}
             */
            this["channels"] = [];
        }
        if (!("summaries" in $$source)) {
            /**
             * 摘要选项列表
             * @member
             * @type {string[]}
             */
            this["summaries"] = [];
        }
        if (!("regions" in $$source)) {
            /**
             * 地区选项列表
             * @member
             * @type {string[]}
             */
            this["regions"] = [];
        }
        if (!("exportPath" in $$source)) {
            /**
             * PDF导出路径（绝对路径）
             * @member
             * @type {string}
             */
            this["exportPath"] = "";
        }
        if (!("addWatermark" in $$source)) {
            /**
             * 导出PDF时是否添加水印
             * @member
             * @type {boolean}
             */
            this["addWatermark"] = false;
        }
        if (!("watermarkPath" in $$source)) {
            /**
             * PDF水印图片路径（PNG）
             * @member
             * @type {string}
             */
            this["watermarkPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemParameters instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemParameters}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("banks" in $$parsedSource) {
            $$parsedSource["banks"] = $$createField0_0($$parsedSource["banks"]);
        }
        if ("depositTypes" in $$parsedSource) {
            $$parsedSource["depositTypes"] = $$createField1_0($$parsedSource["depositTypes"]);
        }
        if ("cashExchanges" in $$parsedSource) {
            $$parsedSource["cashExchanges"] = $$createField2_0($$parsedSource["cashExchanges"]);
        }
        if ("currencies" in $$parsedSource) {
            $$parsedSource["currencies"] = $$createField3_0($$parsedSource["currencies"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField4_0($$parsedSource["channels"]);
        }
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField5_0($$parsedSource["summaries"]);
        }
        if ("regions" in $$parsedSource) {
            $$parsedSource["regions"] = $$createField6_0($$parsedSource["regions"]);
        }
        return new SystemParameters(/** @type {Partial<SystemParameters>} */($$parsedSource));
    }
}

/**
 * TaskPayload 任务数据载荷结构体
 * 包含任务的所有配置参数和业务数据
 */
export class TaskPayload {
    /**
     * Creates a new TaskPayload instance.
     * @param {Partial<TaskPayload>} [$$source = {}] - The source object to create the TaskPayload.
     */
    constructor($$source = {}) {
        if (!("taskName" in $$source)) {
            /**
             * 任务名称
             * @member
             * @type {string}
             */
            this["taskName"] = "";
        }
        if (!("accountName" in $$source)) {
            /**
             * 户名
             * @member
             * @type {string}
             */
            this["accountName"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * 账号（表格中“账号”列）
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("cardNumber" in $$source)) {
            /**
             * 卡号（PDF 顶部银行信息行使用）
             * @member
             * @type {string}
             */
            this["cardNumber"] = "";
        }
        if (!("bank" in $$source)) {
            /**
             * 银行名称
             * @member
             * @type {string}
             */
            this["bank"] = "";
        }
        if (!("dateRange" in $$source)) {
            /**
             * 起止日期范围 [开始日期, 结束日期]
             * @member
             * @type {string[]}
             */
            this["dateRange"] = [];
        }
        if (!("depositType" in $$source)) {
            /**
             * 储种（活期/定期）
             * @member
             * @type {string}
             */
            this["depositType"] = "";
        }
        if (!("currency" in $$source)) {
            /**
             * 币种（人民币/美元）
             * @member
             * @type {string}
             */
            this["currency"] = "";
        }
        if (!("transactionDateRange" in $$source)) {
            /**
             * 交易日期范围 [开始日期, 结束日期]
             * @member
             * @type {string[]}
             */
            this["transactionDateRange"] = [];
        }
        if (!("cashExchange" in $$source)) {
            /**
             * 钞汇类型（钞/汇）
             * @member
             * @type {string}
             */
            this["cashExchange"] = "";
        }
        if (!("channels" in $$source)) {
            /**
             * 渠道列表（多选）
             * @member
             * @type {string[]}
             */
            this["channels"] = [];
        }
        if (!("summaries" in $$source)) {
            /**
             * 摘要列表（多选）
             * @member
             * @type {string[]}
             */
            this["summaries"] = [];
        }
        if (!("openingBalance" in $$source)) {
            /**
             * 起始余额
             * @member
             * @type {number | null}
             */
            this["openingBalance"] = null;
        }
        if (!("amountType" in $$source)) {
            /**
             * 收入/支出金额规则（规则一/规则二）
             * @member
             * @type {string}
             */
            this["amountType"] = "";
        }
        if (!("orderTime" in $$source)) {
            /**
             * 下单时间
             * @member
             * @type {string}
             */
            this["orderTime"] = "";
        }
        if (!("transactionCount" in $$source)) {
            /**
             * 交易笔数（必须大于0）
             * @member
             * @type {number | null}
             */
            this["transactionCount"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * 任务状态：0=未开始, 1=进行中, 2=已完成, 3=已暂停, 4=已取消
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("qrCodeURL" in $$source)) {
            /**
             * 二维码 URL
             * @member
             * @type {string}
             */
            this["qrCodeURL"] = "";
        }
        if (!("startSerialNumber" in $$source)) {
            /**
             * 序号起始值，用于控制消费列表序号（字符串）
             * @member
             * @type {string}
             */
            this["startSerialNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskPayload}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dateRange" in $$parsedSource) {
            $$parsedSource["dateRange"] = $$createField5_0($$parsedSource["dateRange"]);
        }
        if ("transactionDateRange" in $$parsedSource) {
            $$parsedSource["transactionDateRange"] = $$createField8_0($$parsedSource["transactionDateRange"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField10_0($$parsedSource["channels"]);
        }
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField11_0($$parsedSource["summaries"]);
        }
        return new TaskPayload(/** @type {Partial<TaskPayload>} */($$parsedSource));
    }
}

/**
 * TaskProgress 任务进度信息结构体
 * 用于跟踪任务执行的实时进度状态
 */
export class TaskProgress {
    /**
     * Creates a new TaskProgress instance.
     * @param {Partial<TaskProgress>} [$$source = {}] - The source object to create the TaskProgress.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * 任务ID，唯一标识符
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("current" in $$source)) {
            /**
             * 当前已完成的记录数
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * 总记录数
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * 完成百分比 (0-100)
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("isRunning" in $$source)) {
            /**
             * 是否正在运行
             * @member
             * @type {boolean}
             */
            this["isRunning"] = false;
        }
        if (!("isCanceled" in $$source)) {
            /**
             * 是否已取消
             * @member
             * @type {boolean}
             */
            this["isCanceled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * 错误信息（如果有）
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskProgress(/** @type {Partial<TaskProgress>} */($$parsedSource));
    }
}

/**
 * TaskRecord 任务记录结构体
 * 包含任务的元数据（Key、TaskID、创建时间）和任务载荷数据
 */
export class TaskRecord {
    /**
     * Creates a new TaskRecord instance.
     * @param {Partial<TaskRecord>} [$$source = {}] - The source object to create the TaskRecord.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * 数据库存储键，通常与TaskID相同
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("taskId" in $$source)) {
            /**
             * 任务唯一标识符，格式：TASK + 6位数字
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * 任务创建时间
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("taskName" in $$source)) {
            /**
             * 任务名称
             * @member
             * @type {string}
             */
            this["taskName"] = "";
        }
        if (!("accountName" in $$source)) {
            /**
             * 户名
             * @member
             * @type {string}
             */
            this["accountName"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * 账号（表格中“账号”列）
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("cardNumber" in $$source)) {
            /**
             * 卡号（PDF 顶部银行信息行使用）
             * @member
             * @type {string}
             */
            this["cardNumber"] = "";
        }
        if (!("bank" in $$source)) {
            /**
             * 银行名称
             * @member
             * @type {string}
             */
            this["bank"] = "";
        }
        if (!("dateRange" in $$source)) {
            /**
             * 起止日期范围 [开始日期, 结束日期]
             * @member
             * @type {string[]}
             */
            this["dateRange"] = [];
        }
        if (!("depositType" in $$source)) {
            /**
             * 储种（活期/定期）
             * @member
             * @type {string}
             */
            this["depositType"] = "";
        }
        if (!("currency" in $$source)) {
            /**
             * 币种（人民币/美元）
             * @member
             * @type {string}
             */
            this["currency"] = "";
        }
        if (!("transactionDateRange" in $$source)) {
            /**
             * 交易日期范围 [开始日期, 结束日期]
             * @member
             * @type {string[]}
             */
            this["transactionDateRange"] = [];
        }
        if (!("cashExchange" in $$source)) {
            /**
             * 钞汇类型（钞/汇）
             * @member
             * @type {string}
             */
            this["cashExchange"] = "";
        }
        if (!("channels" in $$source)) {
            /**
             * 渠道列表（多选）
             * @member
             * @type {string[]}
             */
            this["channels"] = [];
        }
        if (!("summaries" in $$source)) {
            /**
             * 摘要列表（多选）
             * @member
             * @type {string[]}
             */
            this["summaries"] = [];
        }
        if (!("openingBalance" in $$source)) {
            /**
             * 起始余额
             * @member
             * @type {number | null}
             */
            this["openingBalance"] = null;
        }
        if (!("amountType" in $$source)) {
            /**
             * 收入/支出金额规则（规则一/规则二）
             * @member
             * @type {string}
             */
            this["amountType"] = "";
        }
        if (!("orderTime" in $$source)) {
            /**
             * 下单时间
             * @member
             * @type {string}
             */
            this["orderTime"] = "";
        }
        if (!("transactionCount" in $$source)) {
            /**
             * 交易笔数（必须大于0）
             * @member
             * @type {number | null}
             */
            this["transactionCount"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * 任务状态：0=未开始, 1=进行中, 2=已完成, 3=已暂停, 4=已取消
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("qrCodeURL" in $$source)) {
            /**
             * 二维码 URL
             * @member
             * @type {string}
             */
            this["qrCodeURL"] = "";
        }
        if (!("startSerialNumber" in $$source)) {
            /**
             * 序号起始值，用于控制消费列表序号（字符串）
             * @member
             * @type {string}
             */
            this["startSerialNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskRecord}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dateRange" in $$parsedSource) {
            $$parsedSource["dateRange"] = $$createField8_0($$parsedSource["dateRange"]);
        }
        if ("transactionDateRange" in $$parsedSource) {
            $$parsedSource["transactionDateRange"] = $$createField11_0($$parsedSource["transactionDateRange"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField13_0($$parsedSource["channels"]);
        }
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField14_0($$parsedSource["summaries"]);
        }
        return new TaskRecord(/** @type {Partial<TaskRecord>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
