// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConsumptionRecord 消费记录结构体
 * 表示一条银行交易消费记录，包含交易的所有详细信息
 */
export class ConsumptionRecord {
    /**
     * 数据库存储键，唯一标识符
     */
    "key": string;

    /**
     * 关联的任务ID
     */
    "taskId": string;

    /**
     * 交易日期时间（格式：2006-01-02 15:04:05）
     */
    "tradeDate": string;

    /**
     * 账号
     */
    "account": string;

    /**
     * 储种（活期/定期）
     */
    "storageType": string;

    /**
     * 序号（允许任意字符串）
     */
    "serialNumber": string;

    /**
     * 币种（人民币/美元）
     */
    "currency": string;

    /**
     * 钞汇类型（钞/汇）
     */
    "cashOrRemit": string;

    /**
     * 摘要（消费/工资/银联消费等）
     */
    "summary": string;

    /**
     * 地区（北京/上海/广州等）
     */
    "region": string;

    /**
     * 收入/支出金额（正数为收入，负数为支出）
     */
    "incomeOrExpenseAmount": number;

    /**
     * 余额（累加计算）
     */
    "balance": number;

    /**
     * 渠道（快捷支付/网上银行等）
     */
    "channel": string;

    /** Creates a new ConsumptionRecord instance. */
    constructor($$source: Partial<ConsumptionRecord> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("tradeDate" in $$source)) {
            this["tradeDate"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("storageType" in $$source)) {
            this["storageType"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("cashOrRemit" in $$source)) {
            this["cashOrRemit"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("incomeOrExpenseAmount" in $$source)) {
            this["incomeOrExpenseAmount"] = 0;
        }
        if (!("balance" in $$source)) {
            this["balance"] = 0;
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumptionRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumptionRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumptionRecord($$parsedSource as Partial<ConsumptionRecord>);
    }
}

/**
 * ExportRecord 导出记录结构体
 * 表示一条PDF导出记录
 */
export class ExportRecord {
    /**
     * 数据库存储键，唯一标识符
     */
    "key": string;

    /**
     * 关联的任务ID
     */
    "taskId": string;

    /**
     * PDF文件保存路径
     */
    "filePath": string;

    /**
     * 导出时间
     */
    "createdAt": string;

    /** Creates a new ExportRecord instance. */
    constructor($$source: Partial<ExportRecord> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRecord($$parsedSource as Partial<ExportRecord>);
    }
}

export class PromiseResult {
    "result": string;

    /** Creates a new PromiseResult instance. */
    constructor($$source: Partial<PromiseResult> = {}) {
        if (!("result" in $$source)) {
            this["result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromiseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PromiseResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromiseResult($$parsedSource as Partial<PromiseResult>);
    }
}

/**
 * SystemParameters 系统参数结构体
 * 用于存储系统配置参数，包括各种选项列表
 */
export class SystemParameters {
    /**
     * 银行选项列表
     */
    "banks": string[];

    /**
     * 储种选项列表
     */
    "depositTypes": string[];

    /**
     * 钞汇选项列表
     */
    "cashExchanges": string[];

    /**
     * 币种选项列表
     */
    "currencies": string[];

    /**
     * 渠道选项列表
     */
    "channels": string[];

    /**
     * 摘要选项列表
     */
    "summaries": string[];

    /**
     * 地区选项列表
     */
    "regions": string[];

    /**
     * PDF导出路径（绝对路径）
     */
    "exportPath": string;

    /**
     * 导出PDF时是否添加水印
     */
    "addWatermark": boolean;

    /**
     * PDF水印图片路径（PNG）
     */
    "watermarkPath": string;

    /** Creates a new SystemParameters instance. */
    constructor($$source: Partial<SystemParameters> = {}) {
        if (!("banks" in $$source)) {
            this["banks"] = [];
        }
        if (!("depositTypes" in $$source)) {
            this["depositTypes"] = [];
        }
        if (!("cashExchanges" in $$source)) {
            this["cashExchanges"] = [];
        }
        if (!("currencies" in $$source)) {
            this["currencies"] = [];
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("summaries" in $$source)) {
            this["summaries"] = [];
        }
        if (!("regions" in $$source)) {
            this["regions"] = [];
        }
        if (!("exportPath" in $$source)) {
            this["exportPath"] = "";
        }
        if (!("addWatermark" in $$source)) {
            this["addWatermark"] = false;
        }
        if (!("watermarkPath" in $$source)) {
            this["watermarkPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemParameters instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemParameters {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("banks" in $$parsedSource) {
            $$parsedSource["banks"] = $$createField0_0($$parsedSource["banks"]);
        }
        if ("depositTypes" in $$parsedSource) {
            $$parsedSource["depositTypes"] = $$createField1_0($$parsedSource["depositTypes"]);
        }
        if ("cashExchanges" in $$parsedSource) {
            $$parsedSource["cashExchanges"] = $$createField2_0($$parsedSource["cashExchanges"]);
        }
        if ("currencies" in $$parsedSource) {
            $$parsedSource["currencies"] = $$createField3_0($$parsedSource["currencies"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField4_0($$parsedSource["channels"]);
        }
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField5_0($$parsedSource["summaries"]);
        }
        if ("regions" in $$parsedSource) {
            $$parsedSource["regions"] = $$createField6_0($$parsedSource["regions"]);
        }
        return new SystemParameters($$parsedSource as Partial<SystemParameters>);
    }
}

/**
 * TaskPayload 任务数据载荷结构体
 * 包含任务的所有配置参数和业务数据
 */
export class TaskPayload {
    /**
     * 任务名称
     */
    "taskName": string;

    /**
     * 户名
     */
    "accountName": string;

    /**
     * 账号（表格中“账号”列）
     */
    "account": string;

    /**
     * 卡号（PDF 顶部银行信息行使用）
     */
    "cardNumber": string;

    /**
     * 银行名称
     */
    "bank": string;

    /**
     * 起止日期范围 [开始日期, 结束日期]
     */
    "dateRange": string[];

    /**
     * 储种（活期/定期）
     */
    "depositType": string;

    /**
     * 币种（人民币/美元）
     */
    "currency": string;

    /**
     * 交易日期范围 [开始日期, 结束日期]
     */
    "transactionDateRange": string[];

    /**
     * 钞汇类型（钞/汇）
     */
    "cashExchange": string;

    /**
     * 渠道列表（多选）
     */
    "channels": string[];

    /**
     * 摘要列表（多选）
     */
    "summaries": string[];

    /**
     * 起始余额
     */
    "openingBalance": number | null;

    /**
     * 收入/支出金额规则（规则一/规则二）
     */
    "amountType": string;

    /**
     * 下单时间
     */
    "orderTime": string;

    /**
     * 交易笔数（必须大于0）
     */
    "transactionCount": number | null;

    /**
     * 任务状态：0=未开始, 1=进行中, 2=已完成, 3=已暂停, 4=已取消
     */
    "status": number;

    /**
     * 二维码 URL
     */
    "qrCodeURL": string;

    /**
     * 序号起始值，用于控制消费列表序号（字符串）
     */
    "startSerialNumber": string;

    /** Creates a new TaskPayload instance. */
    constructor($$source: Partial<TaskPayload> = {}) {
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("accountName" in $$source)) {
            this["accountName"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("cardNumber" in $$source)) {
            this["cardNumber"] = "";
        }
        if (!("bank" in $$source)) {
            this["bank"] = "";
        }
        if (!("dateRange" in $$source)) {
            this["dateRange"] = [];
        }
        if (!("depositType" in $$source)) {
            this["depositType"] = "";
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("transactionDateRange" in $$source)) {
            this["transactionDateRange"] = [];
        }
        if (!("cashExchange" in $$source)) {
            this["cashExchange"] = "";
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("summaries" in $$source)) {
            this["summaries"] = [];
        }
        if (!("openingBalance" in $$source)) {
            this["openingBalance"] = null;
        }
        if (!("amountType" in $$source)) {
            this["amountType"] = "";
        }
        if (!("orderTime" in $$source)) {
            this["orderTime"] = "";
        }
        if (!("transactionCount" in $$source)) {
            this["transactionCount"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("qrCodeURL" in $$source)) {
            this["qrCodeURL"] = "";
        }
        if (!("startSerialNumber" in $$source)) {
            this["startSerialNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskPayload {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dateRange" in $$parsedSource) {
            $$parsedSource["dateRange"] = $$createField5_0($$parsedSource["dateRange"]);
        }
        if ("transactionDateRange" in $$parsedSource) {
            $$parsedSource["transactionDateRange"] = $$createField8_0($$parsedSource["transactionDateRange"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField10_0($$parsedSource["channels"]);
        }
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField11_0($$parsedSource["summaries"]);
        }
        return new TaskPayload($$parsedSource as Partial<TaskPayload>);
    }
}

/**
 * TaskProgress 任务进度信息结构体
 * 用于跟踪任务执行的实时进度状态
 */
export class TaskProgress {
    /**
     * 任务ID，唯一标识符
     */
    "taskId": string;

    /**
     * 当前已完成的记录数
     */
    "current": number;

    /**
     * 总记录数
     */
    "total": number;

    /**
     * 完成百分比 (0-100)
     */
    "percent": number;

    /**
     * 是否正在运行
     */
    "isRunning": boolean;

    /**
     * 是否已取消
     */
    "isCanceled": boolean;

    /**
     * 错误信息（如果有）
     */
    "error"?: string;

    /** Creates a new TaskProgress instance. */
    constructor($$source: Partial<TaskProgress> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("isRunning" in $$source)) {
            this["isRunning"] = false;
        }
        if (!("isCanceled" in $$source)) {
            this["isCanceled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskProgress($$parsedSource as Partial<TaskProgress>);
    }
}

/**
 * TaskRecord 任务记录结构体
 * 包含任务的元数据（Key、TaskID、创建时间）和任务载荷数据
 */
export class TaskRecord {
    /**
     * 数据库存储键，通常与TaskID相同
     */
    "key": string;

    /**
     * 任务唯一标识符，格式：TASK + 6位数字
     */
    "taskId": string;

    /**
     * 任务创建时间
     */
    "createdAt": string;

    /**
     * 任务名称
     */
    "taskName": string;

    /**
     * 户名
     */
    "accountName": string;

    /**
     * 账号（表格中“账号”列）
     */
    "account": string;

    /**
     * 卡号（PDF 顶部银行信息行使用）
     */
    "cardNumber": string;

    /**
     * 银行名称
     */
    "bank": string;

    /**
     * 起止日期范围 [开始日期, 结束日期]
     */
    "dateRange": string[];

    /**
     * 储种（活期/定期）
     */
    "depositType": string;

    /**
     * 币种（人民币/美元）
     */
    "currency": string;

    /**
     * 交易日期范围 [开始日期, 结束日期]
     */
    "transactionDateRange": string[];

    /**
     * 钞汇类型（钞/汇）
     */
    "cashExchange": string;

    /**
     * 渠道列表（多选）
     */
    "channels": string[];

    /**
     * 摘要列表（多选）
     */
    "summaries": string[];

    /**
     * 起始余额
     */
    "openingBalance": number | null;

    /**
     * 收入/支出金额规则（规则一/规则二）
     */
    "amountType": string;

    /**
     * 下单时间
     */
    "orderTime": string;

    /**
     * 交易笔数（必须大于0）
     */
    "transactionCount": number | null;

    /**
     * 任务状态：0=未开始, 1=进行中, 2=已完成, 3=已暂停, 4=已取消
     */
    "status": number;

    /**
     * 二维码 URL
     */
    "qrCodeURL": string;

    /**
     * 序号起始值，用于控制消费列表序号（字符串）
     */
    "startSerialNumber": string;

    /** Creates a new TaskRecord instance. */
    constructor($$source: Partial<TaskRecord> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("accountName" in $$source)) {
            this["accountName"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("cardNumber" in $$source)) {
            this["cardNumber"] = "";
        }
        if (!("bank" in $$source)) {
            this["bank"] = "";
        }
        if (!("dateRange" in $$source)) {
            this["dateRange"] = [];
        }
        if (!("depositType" in $$source)) {
            this["depositType"] = "";
        }
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("transactionDateRange" in $$source)) {
            this["transactionDateRange"] = [];
        }
        if (!("cashExchange" in $$source)) {
            this["cashExchange"] = "";
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("summaries" in $$source)) {
            this["summaries"] = [];
        }
        if (!("openingBalance" in $$source)) {
            this["openingBalance"] = null;
        }
        if (!("amountType" in $$source)) {
            this["amountType"] = "";
        }
        if (!("orderTime" in $$source)) {
            this["orderTime"] = "";
        }
        if (!("transactionCount" in $$source)) {
            this["transactionCount"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("qrCodeURL" in $$source)) {
            this["qrCodeURL"] = "";
        }
        if (!("startSerialNumber" in $$source)) {
            this["startSerialNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskRecord {
        const $$createField8_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dateRange" in $$parsedSource) {
            $$parsedSource["dateRange"] = $$createField8_0($$parsedSource["dateRange"]);
        }
        if ("transactionDateRange" in $$parsedSource) {
            $$parsedSource["transactionDateRange"] = $$createField11_0($$parsedSource["transactionDateRange"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField13_0($$parsedSource["channels"]);
        }
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField14_0($$parsedSource["summaries"]);
        }
        return new TaskRecord($$parsedSource as Partial<TaskRecord>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
